name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create additional environment variables
        run: |
          # get the repo name as lower case
          LGITHUB_REPOSITORY=${GITHUB_REPOSITORY,,}
          # remove 'docker-' from the repo name
          echo "::set-env name=DOCKER_REPOSITORY::${LGITHUB_REPOSITORY//docker-/}"
          # get the tag and remove prefix
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF//refs\/tags\//})
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and publish container
        uses: docker/build-push-action@v2
        with:
          build_args: RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}:latest
            ${{ env.DOCKER_REPOSITORY }}:${{ env.RELEASE_VERSION }}
