name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create additional environment variables
        run: |
          # get the repo name as lower case
          LGITHUB_REPOSITORY=${GITHUB_REPOSITORY,,}
          # remove 'docker-' from the repo name
          echo "::set-env name=DOCKER_REPOSITORY::${LGITHUB_REPOSITORY//docker-/}"
          # get the tag and remove prefix
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF//refs\/tags\//})
      - name: Build and publish container
        uses: docker/build-push-action@v1.0.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
